import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3AuthProvider } from "./context/AuthContext";
import { ThemeProvider } from "./context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-light-background dark:bg-dark-background text-light-text dark:text-dark-text`}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Web3AuthProvider>
          {children}
        </Web3AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}